# Generated by Django 6.0.4 on 2026-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_department',
            field=models.CharField(choices=[('A', 'ccsupportfix'), ('B', 'Telephonegram'), ('C', 'Servicenet')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin_department',
            field=models.CharField(choices=[('A', 'ccsupportfix'), ('B', 'Telephonegram'), ('C', 'Servicenet')], max_length=1),
        ),
    ]
