# Generated by Django 6.0.4 on 2026-04-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_userdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartment',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
