# Generated by Django 6.0.4 on 2026-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_userdepartment_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_department',
            field=models.CharField(choices=[('ccsupportfix', 'ccsupportfix'), ('Telephonegram', 'Telephonegram'), ('Servicenet', 'Servicenet')], default='Servicenet', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin_department',
            field=models.CharField(choices=[('ccsupportfix', 'ccsupportfix'), ('Telephonegram', 'Telephonegram'), ('Servicenet', 'Servicenet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdepartment',
            name='department',
            field=models.CharField(choices=[('ccsupportfix', 'ccsupportfix'), ('Telephonegram', 'Telephonegram'), ('Servicenet', 'Servicenet')], max_length=20),
        ),
    ]
