# Generated by Codex on 2026-04-14

from django.db import migrations


def forwards(apps, schema_editor):
    ticket_model = apps.get_model("ticketing", "Ticket")
    user_department_model = apps.get_model("ticketing", "UserDepartment")

    mapping = {
        "A": "ccsupportfix",
        "B": "Telephonegram",
        "C": "Servicenet",
    }

    for old_value, new_value in mapping.items():
        ticket_model.objects.filter(origin_department=old_value).update(origin_department=new_value)
        ticket_model.objects.filter(assigned_department=old_value).update(assigned_department=new_value)
        user_department_model.objects.filter(department=old_value).update(department=new_value)


def backwards(apps, schema_editor):
    ticket_model = apps.get_model("ticketing", "Ticket")
    user_department_model = apps.get_model("ticketing", "UserDepartment")

    reverse_mapping = {
        "ccsupportfix": "A",
        "Telephonegram": "B",
        "Servicenet": "C",
    }

    for old_value, new_value in reverse_mapping.items():
        ticket_model.objects.filter(origin_department=old_value).update(origin_department=new_value)
        ticket_model.objects.filter(assigned_department=old_value).update(assigned_department=new_value)
        user_department_model.objects.filter(department=old_value).update(department=new_value)


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0005_alter_ticket_assigned_department_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
