# Generated by Django 6.0.4 on 2026-04-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_migrate_department_codes_to_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephonegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('თბილისი', 'თბილისი'), ('აჭარა', 'აჭარა'), ('გურია', 'გურია'), ('იმერეთი', 'იმერეთი'), ('კახეთი', 'კახეთი'), ('მცხეთა-მთიანეთი', 'მცხეთა-მთიანეთი'), ('რაჭა-ლეჩხუმი', 'რაჭა-ლეჩხუმი'), ('სამეგრელო-ზემო სვანეთი', 'სამეგრელო-ზემო სვანეთი'), ('სამცხე-ჯავახეთი', 'სამცხე-ჯავახეთი'), ('ქვემო ქართლი', 'ქვემო ქართლი'), ('შიდა ქართლი', 'შიდა ქართლი')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('road_surface', models.CharField(max_length=255)),
                ('responsible_person', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=255)),
                ('send_to', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telephonegram', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['-ticket__created_at'],
            },
        ),
    ]
