# Generated by Django 6.0.4 on 2026-04-21 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_ticket_history_comments(apps, schema_editor):
    TicketComment = apps.get_model("ticketing", "TicketComment")
    TicketHistory = apps.get_model("ticketing", "TicketHistory")

    comments_to_copy = []
    for history_entry in TicketHistory.objects.all().iterator():
        comments_to_copy.append(
            TicketComment(
                ticket_id=history_entry.ticket_id,
                comment=history_entry.comment,
                created_by_id=history_entry.acted_by_id,
                created_at=history_entry.created_at,
            )
        )

    if comments_to_copy:
        TicketComment.objects.bulk_create(comments_to_copy)


def copy_ticket_comments_back(apps, schema_editor):
    TicketComment = apps.get_model("ticketing", "TicketComment")
    TicketHistory = apps.get_model("ticketing", "TicketHistory")

    history_entries = []
    for comment in TicketComment.objects.all().iterator():
        history_entries.append(
            TicketHistory(
                ticket_id=comment.ticket_id,
                event_type="COMMENTED",
                comment=comment.comment,
                acted_by_id=comment.created_by_id,
                created_at=comment.created_at,
            )
        )

    if history_entries:
        TicketHistory.objects.bulk_create(history_entries)


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_telephonegram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(copy_ticket_history_comments, copy_ticket_comments_back),
        migrations.DeleteModel(
            name='TicketHistory',
        ),
    ]
