# Generated by Django 6.0.4 on 2026-04-21 16:03

from django.db import migrations, models


def normalize_ticket_statuses(apps, schema_editor):
    Ticket = apps.get_model("ticketing", "Ticket")
    legacy_open_statuses = [
        "DRAFT",
        "SUBMITTED",
        "UNDER_REVIEW",
        "RETURNED",
    ]
    legacy_closed_statuses = [
        "APPROVED",
        "REJECTED",
    ]

    Ticket.objects.filter(status__in=legacy_open_statuses).update(status="OPEN")
    Ticket.objects.filter(status__in=legacy_closed_statuses).update(status="CLOSED")


def revert_ticket_statuses(apps, schema_editor):
    Ticket = apps.get_model("ticketing", "Ticket")
    Ticket.objects.filter(status="OPEN").update(status="SUBMITTED")
    Ticket.objects.filter(status="CLOSED").update(status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_ticketcomment_delete_tickethistory'),
    ]

    operations = [
        migrations.RunPython(normalize_ticket_statuses, revert_ticket_statuses),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
