# Generated by Django 6.0.4 on 2026-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_telephonegram_telephonegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonegram',
            name='telephonegram_id',
            field=models.PositiveIntegerField(),
        ),
    ]
