# Generated by Django 6.0.4 on 2026-04-29 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_alter_telephonegram_telephonegram_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('DEPARTMENT_CHANGED', 'Department Changed'), ('FIELD_UPDATED', 'Field Updated'), ('COMMENT_ADDED', 'Comment Added'), ('CLOSED', 'Closed')], db_index=True, max_length=30)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['ticket', 'timestamp'], name='ticketing_t_ticket__dbbb75_idx')],
            },
        ),
    ]
